name: test_pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: install
        run: |
          gem install bundler
          bundle install --jobs 1 --retry 2

      - name: test
        run: bundle exec rspec
